const data = {
    products: [
        {
            _id: '1',
            name: 'Nike Slim Shirt',
            category: 'Shirts',
            image: '/images/p1.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Nike',
            rating: 3,
            numReviews: 8,
            description:'high quality product',
        },
        {
            _id: '2',
            name: 'Lacoste Slim Shirt',
            category: 'Shirts',
            image: '/images/p2.jpg',
            price: 100,
            countInStock: 20,
            brand: 'Lacoste',
            rating: 4,
            numReviews: 15,
            description: 'high quality product',
        },
        {
            _id: '3',
            name: 'Nike Slim Shirt',
            category: 'Shirts',
            image: '/images/p3.jpg',
            price: 110,
            countInStock: 0,
            brand: 'Nike',
            rating: 5.0,
            numReviews: 12,
            description: 'high quality product',
        },
        {
            _id: '4',
            name: 'Adidas Slim Pants',
            category: 'Shirts',
            image: '/images/p4.jpg',
            price: 95,
            countInStock: 15,
            brand: 'Adidas',
            rating: 4,
            numReviews: 18,
            description: 'high quality product',
        },
        {
            _id: '5',
            name: 'Puma Slim Pants',
            category: 'Pants',
            image: '/images/p5.jpg',
            price: 80,
            countInStock: 5,
            brand: 'Puma',
            rating: 4.0,
            numReviews: 19,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Nike Slim Pants',
            category: 'Pants',
            image: '/images/p6.jpg',
            price: 50,
            countInStock: 12,
            brand: 'Nike',
            rating: 3.0,
            numReviews: 7,
            description: 'high quality product',
        },
    ],
}
export default data;